version : 0.0
os : linux
files :
  - source : /dist
    destination : /var/www/html
  #  this is where httpd expects our index file to be
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
