version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - node -v
  pre_build:
    commands:
      - echo "we are in pre build phase"
      - node -v
      - npm install
  build:
    commands:
      - echo "we are in build block"
      - echo "we will run some tests"
      - npm run build
  post_build:
    commands:
      - echo "we are in post build phase"

artifacts:
  paths:
    - '**/*'
